#!/bin/bash

# Переменные
MYHOST="AcerOne"
MYUSER="victor3d"

echo "Quick and dirty install of awesome Arch Linux"
read -p "Let the magic begin..."

system_identify()
{
	if [[ $VM ]]; then
		UCODE=''
	elif grep -q 'AuthenticAMD' /proc/cpuinfo; then
		UCODE="amd-ucode"
	elif grep -q 'GenuineIntel' /proc/cpuinfo; then
		UCODE="intel-ucode"
	fi

	if grep -qi 'apple' /sys/class/dmi/id/sys_vendor; then
		modprobe -r -q efivars
	else
		modprobe -q efivarfs
	fi

	if [[ -d /sys/firmware/efi/efivars ]]; then
		export SYS="UEFI"
		grep -q /sys/firmware/efi/efivars /proc/mounts || mount -t efivarfs efivarfs /sys/firmware/efi/efivars
	else
		export SYS="BIOS"
	fi
}

system_identify
echo "System: $SYS"

# Ставим русскую раскладку
loadkeys ru

# Добавим в консоль шрифт, поддерживающий кириллицу
setfont cyr-sun16

#Добавляем русскую локаль
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /etc/locale.gen
locale-gen
export LANG=ru_RU.UTF-8

# Partitioning
#
# 1 - /boot
# 2 - /
# 3 - swap 
# 4 - /home

if [[ $SYS == 'BIOS' ]]; then
	echo "Подготовь разметку диска! После этого примонтируй к /mnt и убери exit"
else
	parted /dev/sda mklabel gpt
	parted -a optimal /dev/sda mkpart fat32 2048s 1024.0
	parted /dev/sda name 1 Boot 
	parted -a optimal /dev/sda mkpart ext2 1024.0 20G
	parted /dev/sda name 2 Root
	parted /dev/sda set 1 boot on
	parted /dev/sda set 1 esp on
	mkfs.fat -F32 /dev/sda1
	mkfs.ext4 /dev/sda2 -L root
	mount /dev/sda2 /mnt
	mkdir /mnt/{boot,home}
	mount /dev/sda1 /mnt/boot
	# mount /dev/sda4 /mnt/home
	# swapon /dev/sda3
fi
# Отредактируй команды по разметке выше или приготовь диск сам после чего удали exit :)
exit

# Выбираем ближайшее зеркало для pacman
sed -i '1 i\Server = http://mirror.yandex.ru/archlinux/$repo/os/$arch' /etc/pacman.d/mirrorlist
 
# Установим базовые пакеты системы.
pacstrap -i /mnt base base-devel $UCODE --noconfirm
# Для тех, кто устанавливает систему через Wi-Fi необходимо также установить пакеты netctl, dialog и wpa_supplicant
pacstrap -i /mnt netctl dialog wpa_supplicant wget reflector --noconfirm
# Установка загрузчика Grub
if [[ $SYS == 'BIOS' ]]; then
	arch-chroot /mnt pacman -S grub-bios --noconfirm
fi

# Дальнейшая настройка системы

# Генерируем fstab, используя следующую команду:
genfstab -p /mnt >> /mnt/etc/fstab

# Работаем в chroot
# arch-chroot /mnt /bin/bash -c "$1"

echo "Добавляем русскую локаль"
sed -i 's/#ru_RU.UTF-8 UTF-8/ru_RU.UTF-8 UTF-8/g' /mnt/etc/locale.gen
sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /mnt/etc/locale.gen
arch-chroot /mnt /bin/bash -c "locale-gen"

echo "Сортировка pacman mirrorlist"
arch-chroot /mnt /bin/bash -c "reflector --score 120 -l 50 -f 20 --sort rate -c RU --save /etc/pacman.d/mirrorlist"

echo "Создание mkinitcpio"
#Добавим русскую локаль в консоль
sed -i "s/block filesystems/block keymap filesystems/g" /mnt/etc/mkinitcpio.conf
# Видеокарта Intel 
sed -i "s/MODULES=()/MODULES=(i915)/g" /mnt/etc/mkinitcpio.conf
# Видеокарта Nvidia
#sed -i 's/MODULES=() /MODULES=(nouveau)/g' /mnt/etc/mkinitcpio.conf
arch-chroot /mnt /bin/bash -c "mkinitcpio -p linux"

echo "Установка загрузчика"
if [[ $SYS == 'BIOS' ]]; then
	arch-chroot /mnt /bin/bash -c "grub-install /dev/sda"
	arch-chroot /mnt /bin/bash -c "grub-mkconfig -o /boot/grub/grub.cfg"
fi
if [[ $SYS == 'UEFI' ]]; then
arch-chroot /mnt /bin/bash -c "bootctl install"
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/boot/loader/entries/arch.conf > /mnt/boot/loader/entries/arch.conf
fi

echo "!!! Установка пароля для ROOT"
arch-chroot /mnt /bin/bash -c "passwd"

#Настраиваем сеть
arch-chroot /mnt /bin/bash -c "systemctl enable dhcpcd"

# Меняем имя компьютера (myhostname меняем на ваше):
echo "$MYHOST" > /mnt/etc/hostname

# Русифицируем нашу систему:

echo "FONT=cyr-sun16" >> /etc/vconsole.conf

cat > /mnt/etc/default/keyboard << EOF
# KEYBOARD CONFIGURATION FILE
# Consult the keyboard(5) manual page.
XKBMODEL=""
XKBLAYOUT="us,ru"
XKBVARIANT=""
XKBOPTIONS="grp:ctrl_shift_toggle"
BACKSPACE="guess"
EOF
	
# Настраиваем временную зону:
arch-chroot /mnt /bin/bash -c "ln -svf /usr/share/zoneinfo/Europe/Simferopol /etc/localtime"

echo "" >> /mnt/etc/pacman.conf
echo "[archlinuxfr]" >> /mnt/etc/pacman.conf
echo "SigLevel = Never" >> /mnt/etc/pacman.conf
echo "Server = http://repo.archlinux.fr/x86_64" >> /mnt/etc/pacman.conf
echo "pacman: раскомментируй [multilib]..."
read -p "После нажатия любой кнопки откроется редактор..."
nano /mnt/etc/pacman.conf
arch-chroot /mnt /bin/bash -c "pacman -Suy --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S --needed --noconfirm base-devel git wget yajl"

echo "Добавим своего пользователя (меняем username на свое) и добавляем его в нужные группы"
arch-chroot /mnt /bin/bash -c "useradd -m -g users -G audio,games,lp,optical,power,scanner,storage,video,wheel -s /bin/bash $MYUSER"
echo "Установим пароль для нашего юзера"
arch-chroot /mnt /bin/bash -c "passwd $MYUSER"
#Добавим ему информацию GECOS:
arch-chroot /mnt /bin/bash -c "chfn victor3d"

# Устанавливаем и настраиваем sudo
arch-chroot /mnt /bin/bash -c "pacman -S sudo --noconfirm"

echo "В файле /etc/sudoers снимаем комментарий со строки # %wheel ALL=(ALL) ALL"
sed -i "s/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g" /mnt/etc/sudoers

arch-chroot /mnt /bin/bash -c "pacman -S xorg-server xorg-xinit mesa-libgl xterm mesa --noconfirm"

# Parallels Desktop Testing
#pacman -S xf86-video-vesa

# Intel 
arch-chroot /mnt /bin/bash -c "pacman -S xf86-video-intel lib32-intel-dri gtk-engine-murrine --noconfirm"

arch-chroot /mnt /bin/bash -c "pacman -S tint2 feh acpi mc nano cdparanoia cdrkit p7zip unrar zip openssh openbox obconf obmenu openbox-themes faenza-icon-theme tangerine-icon-theme pcmanfm file-roller gvfs gnome-menus ntfs-3g dosfstools exfat-utils xbindkeys networkmanager network-manager-applet hicolor-icon-theme gpicview volumeicon --noconfirm"

curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/etc/X11/xorg.conf.d/20-keyboard-layout.conf > /mnt/etc/X11/xorg.conf.d/20-keyboard-layout.conf

# LightDM
arch-chroot /mnt /bin/bash -c "pacman -S lightdm lightdm-gtk-greeter --noconfirm"
arch-chroot /mnt /bin/bash -c "systemctl enable lightdm"
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/etc/lightdm/lightdm-gtk-greeter.conf > /mnt/etc/lightdm/lightdm-gtk-greeter.conf

mkdir -p /mnt/usr/share/images
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/usr/share/images/flowery.jpg > /mnt/usr/share/images/flowery.jpg
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/usr/share/images/linen.png > /mnt/usr/share/images/linen.png

curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/usr/local/bin/i3lock.sh > /mnt/usr/local/bin/i3lock.sh
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/usr/local/bin/mutt.sh > /mnt/usr/local/bin/mutt.sh
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/usr/local/bin/passmenu > /mnt/usr/local/bin/passmenu
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/usr/local/bin/ssh_menu.sh > /mnt/usr/local/bin/ssh_menu.sh
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/usr/local/bin/weather.py > /mnt/usr/local/bin/weather.py
chmod +x /mnt/usr/local/bin/*

arch-chroot /mnt /bin/bash -c "pacman -S xcompmgr conky lxappearance geany ttf-liberation ttf-dejavu opendesktop-fonts ttf-bitstream-vera ttf-arphic-ukai ttf-arphic-uming ttf-hanazono --noconfirm"
arch-chroot /mnt /bin/bash -c "pacman -S cbatticon oblogout xf86-input-synaptics lxterminal transmission-gtk filezilla libva-intel-driver i3lock scrot imagemagick xautolock mcabber mpv htop dmenu xfce4-screenshooter pulseaudio pulseaudio-alsa procmail fetchmail poppler lynx mutt terminator alsa-utils moc gmrun --noconfirm"

# Заполнение skel
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotbashrc > /mnt/etc/skel/.bashrc
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconkyrc > /mnt/etc/skel/.conkyrc
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotfonts.conf > /mnt/etc/skel/.fonts.conf
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotgtkrc-2.0 > /mnt/etc/skel/.gtkrc-2.0
mkdir /mnt/etc/skel/.moc
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotmoc/config > /mnt/etc/skel/.moc/config
mkdir -p /mnt/etc/skel/.config/openbox
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconfig/openbox/autostart > /mnt/etc/skel/.config/openbox/autostart
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconfig/openbox/environment > /mnt/etc/skel/.config/openbox/environment
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconfig/openbox/menu.xml > /mnt/etc/skel/.config/openbox/menu.xml
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconfig/openbox/rc.xml > /mnt/etc/skel/.config/openbox/rc.xml
mkdir /mnt/etc/skel/.config/menus
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconfig/menus/applications.menu > /mnt/etc/skel/.config/menus/applications.menu
mkdir /mnt/etc/skel/.config/dmenu
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconfig/dmenu/dmenu-bind.sh > /mnt/etc/skel/.config/dmenu/dmenu-bind.sh
chmod +x /mnt/etc/skel/.config/dmenu/dmenu-bind.sh
mkdir /mnt/etc/skel/.config/tint2
curl https://raw.githubusercontent.com/victor3dptz/arch-install/master/home/dotconfig/tint2/tint2rc > /mnt/etc/skel/.config/tint2/tint2rc

# AUR
echo "Установка yaourt"
# Хак чтобы работал pacman в chroot
sed -i "s/CheckSpace/#CheckSpace/g" /mnt/etc/pacman.conf
arch-chroot -u $MYUSER /mnt /bin/bash -c "git clone https://aur.archlinux.org/package-query.git /home/$MYUSER/package-query; cd /home/$MYUSER/package-query; makepkg"
arch-chroot /mnt /bin/bash -c "pacman -U /home/$MYUSER/package-query/package-query*.xz --noconfirm"
rm -dR /mnt/home/$MYUSER/package-query/
arch-chroot -u $MYUSER /mnt /bin/bash -c "git clone https://aur.archlinux.org/yaourt.git /home/$MYUSER/yaourt; cd /home/$MYUSER/yaourt/; makepkg"
arch-chroot /mnt /bin/bash -c "pacman -U /home/$MYUSER/yaourt/yaourt*.xz --noconfirm"
rm -dR /mnt/home/$MYUSER/yaourt/


echo "Осталось немножко..."
# Bunsen Themes
arch-chroot -u $MYUSER /mnt /bin/bash -c "git clone https://aur.archlinux.org/bunsen-themes-git.git /home/$MYUSER/bunsen-themes-git; cd /home/$MYUSER/bunsen-themes-git; makepkg"
arch-chroot /mnt /bin/bash -c "pacman -U /home/$MYUSER/bunsen-themes-git/bunsen-themes-git*.xz --noconfirm"
rm -dR /mnt/home/$MYUSER/bunsen-themes-git/

# Вернем взад настройку pacman
sed -i "s/#CheckSpace/CheckSpace/g" /mnt/etc/pacman.conf

#yaourt -S links-g-directfb
#gpg --keyserver=keyserver.ubuntu.com --recv-keys 865E6C87C65285EC
#yaourt -S palemoon-bin palemoon-i18n-ru

echo "Все готово! Перезагрузись и кайфуй!"